roots/wordpress-packager

composer.json, composer.lock, phpstan.neon, src/WordPressPackager/ReleaseSources/WPDotOrgHTML.php, src/WordPressPackager/WordPressPackage.php
Using PHPStan is a personal preference. I find it more helpful than codeclimate and scrutinizer.
=> Add PHPStan

.dependabot/config.yml, Makefile, README.md, build/app/Dockerfile, build/base/Dockerfile, build/dev/Dockerfile, build/install-composer.sh
targets the WIP circleci branch
=> Adds docker images and makefile

.circleci/config.yml, .gitignore, phpunit.xml
=> Add CircleCI config

.dependabot/config.yml
=> Dependabot on top level deps only

.dependabot/config.yml
live seems like lots of merge conflicts and lots of daily work keeping this up to date
=> weekly composer update

composer.json, composer.lock, src/WordPressPackager/ReleaseSources/WPDotOrgHTML.php, src/WordPressPackager/WordPressPackage.php, test/WordPressPackager/ReleaseSources/WPDotOrgHTMLTest.php, test/WordPressPackager/WordPressPackageRepositoryTest.php
- use symphony/dom-crawler for better html5 support
- use league/uri packages for more stable url parsing
- 100% test coverage
- various code quality improvements
=> Better HTML and URL parsing

src/WordPressPackager/WordPressPackage.php
First round for PHP extensions.
Need to extract required ones, but hard to say exactly which.
Fix #40
=> Add PHP extensions suggestion

bin/build, composer.json, composer.lock, src/WordPressPackager/Build.php, src/WordPressPackager/License.php, src/WordPressPackager/PackageWriter.php, src/WordPressPackager/Target.php, src/WordPressPackager/Util/Directory.php, test/WordPressPackager/LicenseTest.php, test/WordPressPackager/PackageWriterTest.php, test/WordPressPackager/TargetTest.php, test/WordPressPackager/Util/DirectoryTest.php
```bash
composer install
./bin/build <git-remote>
```
Example:
```bash
composer install
./bin/build git@github.com:TangRufus/testing-roots-wordpress-packager.git
./bin/build https://github.com/TangRufus/testing-roots-wordpress-packager.git
./bin/build /path/to/local/git/repo
```
```bash
composer run-script --timeout=<seconds> build <git-remote>
```
Example:
```bash
composer run-script --timeout=1800 build git@github.com:TangRufus/testing-roots-wordpress-packager.git
composer run-script --timeout=1800 build https://github.com/TangRufus/testing-roots-wordpress-packager.git
composer run-script --timeout=1800 build /path/to/local/git/repo
```
https://github.com/TangRufus/testing-roots-wordpress-packager
---
Config: https://github.com/TangRufus/testing-roots-wordpress-packager/blob/build/.circl …
=> Add build script

.circleci/config.yml, composer.json, phpcs.xml, test/E2E/WPDotOrgHTMLTestE2E.php, test/WordPressPackager/ReleaseSources/WPDotOrgHTMLTest.php, test/WordPressPackager/WordPressPackageRepositoryTest.php, test/WordPressPackager/WordPressPackageTest.php
And apply it on every PHP filesin the repo
=> Use PSR 12 when linting

.codeclimate.yml, .github/workflows/test.yml, src/Package/Package.php, src/ReleaseSources/WPDotOrgAPI.php, tests/Package/PacakgeTest.php, tests/Package/PackageTest.php, tests/resources/composer.json
* Adds the `provides` field
* Improve version constraints
* Cleaner and more tested API
=> Improved packages metadata

.github/workflows/auto-merge.yml
With the following conditions:
* Auto-merge is enabled for the repository
* PR are "protected" by one mandatory review and a mandatory test job
* The checks are successful
* The version change is not major
=> Add a workflow to merge automatically Dependabot request

src/Target.php, tests/TargetTest.php
Closes #483
See https://github.com/czproject/git-php/issues/77
=> Fix `GitRepository` usage

src/ReleaseSources/WPDotOrgAPI.php, tests/resources/source-composer.json
Closes https://github.com/roots/wordpress/issues/41
=> Add source attribute on generated packages

.github/workflows/meta-package.yml
Validated, tested, debugged, optimized.
Hopefully the last good-to-go shot.
---
Thanks for the follow up on these additional PRs, debugging GitHub Actions is not that easy 😭
=> Rework the tags comparaison

.github/workflows/meta-package.yml
Aaaand this is the last one!
Everything is working well, just a clean up and and little fix on conditional validation. 👌
=> Enforce output validation in meta-package workflow

.github/workflows/meta-package.yml
=> Secrets are not allowed to be defined as job output

.github/workflows/meta-package.yml
I'm not giving up, I'm not giving up
=> Create the tag manually and drop dependency

.github/workflows/meta-package.yml
That one was obvious.
It's going to be a relief to see it working.
=> Setup a git user to allow tag pushes

.github/workflows/meta-package.yml
🎉 All the rest was working great! 🎉
=> The final mismatch

.github/workflows/run.yml
Follow up of https://github.com/roots/wordpress-packager/pull/617
=> Fix actions deprecation warning
